### ISSUE TITLE
Need help with HmIP-RF-USB-TK

### ISSUE THREAD

**Issue by Jerac102** [alexreinert/debmatic#155]
Hi, 

 i am new to debmatic and i have a problem to configure it with HmIP-RF-USB-TK.
I have connected usb stick into laptop and in debmatic apper CCU as connected device.
When i try to Teach-on device, non of two methods works (devices: 2 x hmip-etrv-b that are currently connected to HmIP-HAP).
I didn't do any extra configurations of debmatic, just plugged USB stick.
I need help ho to teach on devices.
Next step is HomeAssistant where i want to connect debmatic or maybe use HomeMatic CCU addon?

Thanks fo the help.

Also i saw a Exception in  logs that is repeating every 1 minute:

`Oct 21 06:34:58 de.eq3.cbcs.lib.backbone.lanrouting.BackboneWorker ERROR [vert.x-worker-thread-3] AP 3014F5AC94000416FB533A8C: Could not parse outgoing routing frame
de.eq3.cbcs.util.core.InvalidParameterLengthException: The parameter key must be 16 byte long
    at de.eq3.cbcs.util.core.ByteArrayUtils.validateParameterLength(ByteArrayUtils.java:200)
    at de.eq3.cbcs.util.core.CbcMacAes.calculateMIC(CbcMacAes.java:423)
    at de.eq3.cbcs.lib.backbone.lanrouting.BackboneWorker.sendBackboneFrameToBackbone(BackboneWorker.java:773)
    at de.eq3.cbcs.lib.backbone.lanrouting.BackboneWorker.lambda$start$16(BackboneWorker.java:132)
    at io.vertx.core.eventbus.impl.HandlerRegistration.deliver(HandlerRegistration.java:212)
    at io.vertx.core.eventbus.impl.HandlerRegistration.handle(HandlerRegistration.java:191)
    at io.vertx.core.eventbus.impl.EventBusImpl.lambda$deliverToHandler$3(EventBusImpl.java:505)
    at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:337)
    at io.vertx.core.impl.TaskQueue.lambda$new$0(TaskQueue.java:60)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
    at java.base/java.lang.Thread.run(Thread.java:832)
`
My configuration: 

1. Ubuntu 20.04 LTS
2. debmatic
3. HmIP-RF-USB-TK

**Comment by Jerac102** [comment]
I have connected my device. The problem was that i wasn't reset device properly. Exception doesn't have nothing to do with it. Next stet is to integrate debmatic with Home Assistent. Any tipps for me?
