### ISSUE TITLE
RPI-RF_MOD wird nicht mehr erkannt

### ISSUE THREAD

**Issue by ChristianRiedl** [alexreinert/debmatic#373]
3 Monate lang hat mein PI 3 B+ mit dem RPI-RF-MOD klaglos funktioniert. Dann ist er ausgefallen weil das Filesystem irreparabel beschädigt war. Also habe ich alles neu installiert, seither wird offensichtlich das RPI-RF_MOD nicht mehr erkannt. Das Web UI kommt normal hoch und ich sehe die importierten Geräte aber bekomme keinen aktuellen Status. Es könnte natürlich sein, dass das RPI-RF-MOD defekt geworden ist, in der Folge dann extrem viel geloggt wurde und dabei das Filesystem zerstört worden ist. Leider konnte ich das nicht mehr analysieren weil der PI nicht mehr hochkam. Haben sie eine Idee wie ich da weiterkomme ?  

sudo debmatic-info liefert :
```
debmatic version: 3.73.9-112
OS:               Debian GNU/Linux 12 (bookworm)
Kernel:           6.1.0-rpi8-rpi-v8 aarch64
Service Status:   Running
Kernel modules:   Available
Raw UART dev:     Not available
Rasp.Pi UART:     Not assigned to GPIO pins
HMRF Hardware:    unknown
HMIP Hardware:    unknown 
```

cat hm_mode liefert : (der Rest ist auch '')
```
HM_HOST='debmatic'
HM_MODE='NORMAL'
HM_LED_GREEN=''
HM_LED_GREEN_MODE1='none'
HM_LED_GREEN_MODE2='none'
HM_LED_RED=''
HM_LED_RED_MODE1='none'
HM_LED_RED_MODE2='none'
HM_LED_YELLOW=''
HM_LED_YELLOW_MODE1='none'
HM_LED_YELLOW_MODE2='none'
HM_HOST_GPIO_UART=''
HM_HOST_GPIO_RESET=''
HM_RTC=''
HM_HMIP_DEV=''
etc.
```

Hier noch hmserver.log :
```
2024-02-25 19:05:23,161 de.eq3.lib.util.dynamics.GenericFactory INFO  [main] @GenericFactory
2024-02-25 19:05:23,193 de.eq3.lib.util.dynamics.GenericFactory INFO  [main] created instance of HMServerConfiguration with parameter(s)
2024-02-25 19:05:23,194 de.eq3.lib.util.dynamics.GenericFactory INFO  [main] passed 1 parameter(s), in declarative order [String]
2024-02-25 19:05:23,198 de.eq3.ccu.server.BaseHMServer INFO  [main] Creating instance of HMServer...
2024-02-25 19:05:23,208 de.eq3.cbcs.util.EQ3LoggerOutputStream INFO  [main] std.out and std.err redirection active
2024-02-25 19:05:23,310 de.eq3.ccu.server.BaseHMServer INFO  [main] Default MaxEventLoopExecuteTime: 2000000000
2024-02-25 19:05:23,312 de.eq3.ccu.server.BaseHMServer INFO  [main] Default BlockedThreadCheckInterval: 1000
2024-02-25 19:05:23,313 de.eq3.ccu.server.BaseHMServer INFO  [main] Default MaxWorkerExecuteTime: 60000000000
2024-02-25 19:05:23,316 de.eq3.ccu.server.BaseHMServer INFO  [main] Default EventLoopPoolSize: 8
2024-02-25 19:05:24,512 de.eq3.vertx.manager.management.VertxManager INFO  [main] SYSTEM: added for deployment [BackendWorker] (1) *worker
2024-02-25 19:05:24,514 de.eq3.vertx.manager.management.VertxManager INFO  [main] SYSTEM: added for deployment [GroupRequestWorker] (1) *worker
2024-02-25 19:05:24,517 de.eq3.vertx.manager.management.VertxManager INFO  [main] SYSTEM: added for deployment [DiagramRequestWorker] (1) *worker
2024-02-25 19:05:24,519 de.eq3.vertx.manager.management.VertxManager INFO  [main] SYSTEM: added for deployment [StorageRequestWorker] (1) *worker
2024-02-25 19:05:24,522 de.eq3.vertx.manager.management.VertxManager INFO  [main] SYSTEM: added for deployment [DeviceFirmwareRequestWorker] (1) *worker
2024-02-25 19:05:24,524 de.eq3.vertx.manager.management.VertxManager INFO  [main] SYSTEM: added for deployment [EnergyPriceRequestWorker] (1) *worker
2024-02-25 19:05:24,527 de.eq3.vertx.manager.management.VertxManager INFO  [main] SYSTEM: added for deployment [CouplingRequestWorker] (1) *worker
2024-02-25 19:05:24,529 de.eq3.vertx.manager.management.VertxManager INFO  [main] SYSTEM: added for deployment [RegaClientWorker] (1) *worker
2024-02-25 19:05:24,532 de.eq3.vertx.manager.management.VertxManager INFO  [main] SYSTEM: added for deployment [GroupConfigurationPersistenceFileSystem] (1) *worker
2024-02-25 19:05:24,562 de.eq3.vertx.manager.management.VertxManager INFO  [main] SYSTEM: deploying 9 classes to Vert.x
2024-02-25 19:05:24,635 de.eq3.vertx.manager.management.VertxManager INFO  [main] SYSTEM: 9 VertxDeployers initialized
2024-02-25 19:05:24,966 de.eq3.vertx.manager.management.VertxManager INFO  [vert.x-eventloop-thread-1] SYSTEM: start of CouplingRequestWorker succeeded (88c6382e-a2f2-431a-a7d5-79640c5006f8)
2024-02-25 19:05:24,968 de.eq3.vertx.manager.management.VertxManager INFO  [vert.x-eventloop-thread-2] SYSTEM: start of GroupConfigurationPersistenceFileSystem succeeded (dd2a5994-8303-420c-9d49-1e374b06db0b)
2024-02-25 19:05:24,966 de.eq3.vertx.manager.management.VertxManager INFO  [vert.x-eventloop-thread-0] SYSTEM: start of EnergyPriceRequestWorker succeeded (e1dfa4d5-6121-4e95-a17d-1f41dec8e6b0)
2024-02-25 19:05:24,977 de.eq3.vertx.manager.management.VertxManager INFO  [vert.x-eventloop-thread-2] SYSTEM: start of BackendWorker succeeded (be3cb10b-8728-405b-98d9-147d63ef09d4)
2024-02-25 19:05:24,984 de.eq3.vertx.manager.management.VertxManager INFO  [vert.x-eventloop-thread-4] SYSTEM: start of StorageRequestWorker succeeded (0cdaff85-622c-426a-9edb-7f4df00fa780)
2024-02-25 19:05:24,991 de.eq3.vertx.manager.management.VertxManager INFO  [vert.x-eventloop-thread-3] SYSTEM: start of RegaClientWorker succeeded (15475320-39e8-4276-b424-c6b185b80ebd)
2024-02-25 19:05:25,213 de.eq3.vertx.manager.management.VertxManager INFO  [vert.x-eventloop-thread-1] SYSTEM: start of GroupRequestWorker succeeded (4fe96e6b-a3a5-4dda-b531-0eb2e2f3b39f)
2024-02-25 19:05:25,216 de.eq3.vertx.manager.management.VertxManager INFO  [vert.x-eventloop-thread-3] SYSTEM: start of DiagramRequestWorker succeeded (3a6967d8-8b09-4a2d-9c78-363e709c7233)
2024-02-25 19:05:25,217 de.eq3.vertx.manager.management.VertxManager INFO  [vert.x-eventloop-thread-5] SYSTEM: start of DeviceFirmwareRequestWorker succeeded (f16b0033-bc0d-47ef-be4f-c0004b2d562f)
2024-02-25 19:05:25,248 de.eq3.vertx.manager.management.VertxManager INFO  [main] SYSTEM: initial deployment complete _____________________________________________________
2024-02-25 19:05:25,281 de.eq3.ccu.server.BaseHMServer INFO  [main] Starting HMServer at 127.0.0.1:39292
2024-02-25 19:05:25,283 de.eq3.ccu.server.BaseHMServer INFO  [main] Read Configuration
2024-02-25 19:05:25,700 de.eq3.ccu.server.BaseHMServer INFO  [main] Create Bidcos Dispatcher
2024-02-25 19:05:25,770 de.eq3.ccu.server.BaseHMServer INFO  [main] InitBidCosCache
2024-02-25 19:05:25,772 de.eq3.ccu.server.BaseHMServer INFO  [main] Create groupDefinitionProvider
2024-02-25 19:05:28,025 de.eq3.ccu.server.BaseHMServer INFO  [main] Create VirtualDeviceHolder
2024-02-25 19:05:28,046 de.eq3.ccu.server.BaseHMServer INFO  [main] Create VirtualDeviceHandlerRega
2024-02-25 19:05:28,061 de.eq3.ccu.server.BaseHMServer INFO  [main] Create GroupAdministrationService
2024-02-25 19:05:28,062 de.eq3.ccu.server.BaseHMServer INFO  [main] Create GroupDeviceDispatcher
2024-02-25 19:05:28,066 de.eq3.ccu.server.BaseHMServer INFO  [main] Create GroupDeviceHandler
2024-02-25 19:05:28,077 de.eq3.ccu.groupdevice.service.GroupDeviceHandler INFO  [main] @GroupDeviceHandler - initializing...
2024-02-25 19:05:28,078 de.eq3.ccu.groupdevice.service.GroupDeviceHandler INFO  [main] --> created groupDeviceDispatcher (GroupDeviceService to BidCoS (via Dispatcher))
2024-02-25 19:05:28,079 de.eq3.ccu.groupdevice.service.GroupDeviceHandler INFO  [main] --> created virtualDeviceHandler (GroupDeviceService to ReGa)
2024-02-25 19:05:28,080 de.eq3.ccu.groupdevice.service.GroupDeviceHandler INFO  [main] --> got groupDefinitionProvider
2024-02-25 19:05:28,082 de.eq3.ccu.server.BaseHMServer INFO  [main] Create BidCosGroupMemberProvider
2024-02-25 19:05:28,132 de.eq3.ccu.server.BaseHMServer INFO  [main] Init groupAdministrationService
2024-02-25 19:05:28,139 de.eq3.ccu.server.BaseHMServer INFO  [main] Init Virtual OS Device
2024-02-25 19:05:28,149 de.eq3.ccu.server.BaseHMServer INFO  [main] Init ESHLight Bridge
2024-02-25 19:05:29,953 de.eq3.ccu.server.BaseHMServer INFO  [main] Create RrdDatalogging
2024-02-25 19:05:29,965 de.eq3.ccu.server.BaseHMServer INFO  [main] Create MeasurementService
2024-02-25 19:05:29,975 de.eq3.ccu.server.BaseHMServer INFO  [main] Init MeasurementService
2024-02-25 19:05:30,179 de.eq3.ccu.server.BaseHMServer INFO  [main] Create HTTP Server
2024-02-25 19:05:34,125 de.eq3.ccu.server.BaseHMServer INFO  [main] Create BidCos context and start handler
2024-02-25 19:05:34,419 de.eq3.ccu.server.BaseHMServer INFO  [main] Create group context and start handler
2024-02-25 19:05:35,449 de.eq3.ccu.server.BaseHMServer INFO  [main] Starting HMServer done
2024-02-25 19:05:44,314 de.eq3.ccu.virtualdevice.service.internal.rega.VirtualDeviceHandlerRega INFO  [vert.x-eventloop-thread-1] (un)registerCallback on VirtualDeviceHandlerRega called from url: xmlrpc_bin://127.0.0.1:31999
2024-02-25 19:05:44,354 de.eq3.ccu.virtualdevice.service.internal.rega.VirtualDeviceHandlerRega INFO  [vert.x-eventloop-thread-1] Added InterfaceId: 1007
2024-02-25 19:05:44,365 de.eq3.ccu.virtualdevice.service.internal.rega.BackendWorker INFO  [vert.x-worker-thread-9] Execute BackendCommand: de.eq3.ccu.virtualdevice.service.internal.rega.BackendUpdateDevicesCommand
2024-02-25 19:05:46,967 io.vertx.core.impl.BlockedThreadChecker WARN  [vertx-blocked-thread-checker] Thread Thread[vert.x-eventloop-thread-1,5,main] has been blocked for 2672 ms, time limit is 2000 ms
2024-02-25 19:05:47,959 io.vertx.core.impl.BlockedThreadChecker WARN  [vertx-blocked-thread-checker] Thread Thread[vert.x-eventloop-thread-1,5,main] has been blocked for 3672 ms, time limit is 2000 ms
2024-02-25 19:05:48,959 io.vertx.core.impl.BlockedThreadChecker WARN  [vertx-blocked-thread-checker] Thread Thread[vert.x-eventloop-thread-1,5,main] has been blocked for 4672 ms, time limit is 2000 ms
2024-02-25 19:05:49,962 io.vertx.core.impl.BlockedThreadChecker WARN  [vertx-blocked-thread-checker] Thread Thread[vert.x-eventloop-thread-1,5,main] has been blocked for 5672 ms, time limit is 2000 ms
io.vertx.core.VertxException: Thread blocked
        at jdk.internal.misc.Unsafe.park(Native Method) ~[?:?]
        at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:252) ~[?:?]
        at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:1672) ~[?:?]
        at java.util.concurrent.LinkedBlockingQueue.poll(LinkedBlockingQueue.java:460) ~[?:?]
        at de.eq3.ccu.virtualdevice.service.internal.rega.VirtualDeviceHandlerRega.registerCallback(VirtualDeviceHandlerRega.java:99) ~[HMServer.jar:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at de.eq3.cbcs.legacy.communication.rpc.internal.rpc.AnnotationAwareRpcHandler.execute(AnnotationAwareRpcHandler.java:80) ~[HMServer.jar:?]
        at de.eq3.ccu.server.internal.RpcMessageHandler.handle(RpcMessageHandler.java:70) ~[HMServer.jar:?]
        at de.eq3.ccu.server.internal.RpcMessageHandler.handle(RpcMessageHandler.java:24) ~[HMServer.jar:?]
        at io.vertx.core.impl.EventLoopContext.emit(EventLoopContext.java:50) ~[HMServer.jar:?]
        at io.vertx.core.impl.DuplicatedContext.emit(DuplicatedContext.java:168) ~[HMServer.jar:?]
        at io.vertx.core.eventbus.impl.MessageConsumerImpl.dispatch(MessageConsumerImpl.java:187) ~[HMServer.jar:?]
        at io.vertx.core.eventbus.impl.HandlerRegistration$InboundDeliveryContext.next(HandlerRegistration.java:162) ~[HMServer.jar:?]
        at io.vertx.core.eventbus.impl.HandlerRegistration$InboundDeliveryContext.dispatch(HandlerRegistration.java:127) ~[HMServer.jar:?]
        at io.vertx.core.eventbus.impl.HandlerRegistration$$Lambda$210/0x000000280133fa20.run(Unknown Source) ~[?:?]
        at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:111) ~[HMServer.jar:?]
        at io.vertx.core.eventbus.impl.HandlerRegistration.dispatch(HandlerRegistration.java:103) ~[HMServer.jar:?]
        at io.vertx.core.eventbus.impl.MessageConsumerImpl.deliver(MessageConsumerImpl.java:193) ~[HMServer.jar:?]
        at io.vertx.core.eventbus.impl.MessageConsumerImpl.doReceive(MessageConsumerImpl.java:178) ~[HMServer.jar:?]
        at io.vertx.core.eventbus.impl.HandlerRegistration.lambda$receive$0(HandlerRegistration.java:54) ~[HMServer.jar:?]
        at io.vertx.core.eventbus.impl.HandlerRegistration$$Lambda$209/0x000000280133f590.run(Unknown Source) ~[?:?]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164) ~[HMServer.jar:?]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469) ~[HMServer.jar:?]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:497) ~[HMServer.jar:?]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) ~[HMServer.jar:?]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[HMServer.jar:?]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[HMServer.jar:?]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]
2024-02-25 19:05:50,961 io.vertx.core.impl.BlockedThreadChecker WARN  [vertx-blocked-thread-checker] Thread Thread[vert.x-eventloop-thread-1,5,main] has been blocked for 6673 ms, time limit is 2000 ms
io.vertx.core.VertxException: Thread blocked
```

**Comment by ChristianRiedl** [comment]
Alles zurück !!
Ich habe beim installieren einen Schritt übersehen (Serielle Konsole deaktivieren).
